### ISSUE TITLE
pytorch_lightning.utilities.exceptions.MisconfigurationException:                  You requested GPUs: [0]                 But your machine only has: [

### ISSUE THREAD

**Issue by trinh-hoang-hiep** [declare-lab/dialog-HGAT#2]
Thank you for sharing the code, it is really neat and helpful. But when i run it, i meet thi error
python main.py
Using backend: pytorch
LOADING dialogre dataset
LOADING dialogre dataset for conversation setting
Finetune all word embeddings
DGL backend not selected or invalid.  Assuming PyTorch for now.
Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)
Using backend: pytorch
2020-11-22 04:06:31.661428: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
/usr/local/lib/python3.6/dist-packages/spacy/util.py:275: UserWarning: [W031] Model 'en_core_web_sm' (2.2.5) requires spaCy v2.2 and is incompatible with the current spaCy version (2.3.2). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
LOADING dialogre dataset
LOADING dialogre dataset for conversation setting
Finetune all word embeddings
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    trainer = Trainer(**trainer_args, resume_from_checkpoint=config.ckpt_path if config.ckpt_path else None)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 511, in __init__
    self.data_parallel_device_ids = _parse_gpu_ids(self.gpus)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 361, in _parse_gpu_ids
    gpus = sanitize_gpu_ids(gpus)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 320, in sanitize_gpu_ids
    """)
pytorch_lightning.utilities.exceptions.MisconfigurationException: 
                You requested GPUs: [0]
                But your machine only has: []
            
I'm newbie in cuda , when i run nvidia-smi  i met this error
nvidia-smi 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.38       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8    10W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by Emrys-Hong** [comment]
Hi Thank you for asking.

It looks like you cuda driver is not working. You will need cuda driver to run pytorch with gpu. To install cuda driver, you can follow below for convenience:
1. Start terminal and remove any NVIDIA traces you may have on your machine.
```
sudo rm /etc/apt/sources.list.d/cuda*
sudo apt remove --autoremove nvidia-cuda-toolkit
sudo apt remove --autoremove nvidia-*
```
2. Install CUDA 10.1 follow the nvidia official website: 
https://developer.nvidia.com/cuda-10.1-download-archive-base

You can use `nvidia-smi` to verify installation.

**Comment by trinh-hoang-hiep** [comment]
> Hi Thank you for asking.
> 
> It looks like you cuda driver is not working. You will need cuda driver to run pytorch with gpu. To install cuda driver, you can follow below for convenience:
> 
>     1. Start terminal and remove any NVIDIA traces you may have on your machine.
> 
> 
> ```
> sudo rm /etc/apt/sources.list.d/cuda*
> sudo apt remove --autoremove nvidia-cuda-toolkit
> sudo apt remove --autoremove nvidia-*
> ```
> 
>     1. Install CUDA 10.1 follow the nvidia official website:
>        https://developer.nvidia.com/cuda-10.1-download-archive-base
> 
> 
> You can use `nvidia-smi` to verify installation.

Thank you for answer, 
When i run 
nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.38 Driver Version: 418.67 CUDA Version: 10.1 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
| | | MIG M. |
|===============================+======================+======================|
| 0 Tesla T4 Off | 00000000:00:04.0 Off | 0 |
| N/A 53C P8 10W / 70W | 0MiB / 15079MiB | 0% Default |
| | | ERR! |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: |
| GPU GI CI PID Type Process name GPU Memory |
| ID ID Usage |
|=============================================================================|
| No running processes found |
+-----------------------------------------------------------------------------+

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243


i installed pip install --pre dgl-cu101  

Using backend: pytorch
2020-11-22 04:27:26.641719: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
/usr/local/lib/python3.6/dist-packages/spacy/util.py:275: UserWarning: [W031] Model 'en_core_web_sm' (2.2.5) requires spaCy v2.2 and is incompatible with the current spaCy version (2.3.2). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
LOADING dialogre dataset
LOADING dialogre dataset for conversation setting
Finetune all word embeddings
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    trainer = Trainer(**trainer_args, resume_from_checkpoint=config.ckpt_path if config.ckpt_path else None)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 511, in __init__
    self.data_parallel_device_ids = _parse_gpu_ids(self.gpus)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 361, in _parse_gpu_ids
    gpus = sanitize_gpu_ids(gpus)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 320, in sanitize_gpu_ids
    """)
pytorch_lightning.utilities.exceptions.MisconfigurationException: 
                You requested GPUs: [0]
                But your machine only has: []

**Comment by trinh-hoang-hiep** [comment]
when i run
import torch
print(torch.cuda.device_count())
it return 0

**Comment by Emrys-Hong** [comment]
`torch.cuda.device_count() = 0` means you are still not able to use gpu on pytorch. You can refer to my comment above for cuda reinstallation.

**Comment by trinh-hoang-hiep** [comment]
i reinstalled it, and it can run <3 Thank you
